# Generated by Django 3.2.5 on 2021-07-11 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=225, verbose_name='Номер телефона')),
                ('ver_code', models.CharField(max_length=225, verbose_name='Код верефикации ClientAPI')),
                ('auth_code', models.CharField(max_length=225, verbose_name='Код аунтификации Telegram')),
                ('session_link', models.CharField(editable=False, max_length=225)),
                ('api_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('api_hash', models.CharField(blank=True, editable=False, max_length=225, null=True)),
                ('status', models.BooleanField(default=False, editable=False)),
                ('bot_type', models.CharField(choices=[('MAILER', 'Для рассылок'), ('INVITER', 'Для инвайтинга')], max_length=225, verbose_name='Тип бота')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
                'db_table': 'bot',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Название группы')),
                ('link', models.CharField(max_length=225, verbose_name='Ссылка на группу')),
            ],
            options={
                'verbose_name': 'Группа для парсинга',
                'verbose_name_plural': 'Группы для парсинга',
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='RandHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_full_name', models.CharField(max_length=225, verbose_name='Имя пользователя')),
                ('username', models.CharField(blank=True, max_length=225, null=True, verbose_name='Юзернейм')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_mailer.group', verbose_name='Получен из группы')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Parsing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True, verbose_name='Название')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_mailer.group', verbose_name='Группа для парсинга')),
            ],
            options={
                'verbose_name': 'Парсинг',
                'verbose_name_plural': 'Парсинг',
                'db_table': 'parsing',
            },
        ),
        migrations.CreateModel(
            name='Mailings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_mailer.group', verbose_name='Рассылка по группе')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'db_table': 'mailing',
            },
        ),
        migrations.CreateModel(
            name='Inviting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True, verbose_name='Название')),
                ('group', models.CharField(max_length=225, verbose_name='Приглашать в группу (ссылка)')),
                ('users_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_mailer.group', verbose_name='Приглашать пользователей из парсинг-группы')),
            ],
            options={
                'verbose_name': 'Инвайтинг',
                'verbose_name_plural': 'Инвайтинг',
                'db_table': 'inviting',
            },
        ),
    ]
