# Generated by Django 3.2.5 on 2021-07-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='banned_to',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
