# Generated by Django 3.2.5 on 2021-07-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_mailer', '0002_bot_banned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='banned_to',
        ),
    ]
